/* ============================================================
   La Mia Libreria — dati iniziali
   I titoli presenti in più elenchi compaiono una volta sola,
   con più categorie assegnate.
   Campi: t=titolo, a=autrice, c=categorie, fav=preferito,
          read=letto, nope=non piaciuto, vt=volumi totali,
          vc=volume attuale, pc=pagina attuale, pt=pagine totali, n=note
   ============================================================ */
(function () {
  const ATT = 'attesa', AUT = 'autrici', LET = 'letti', FIN = 'dafinire',
        FOR = 'forse', PRE = 'preferiti', SOS = 'sospesi';

  const categories = [
    { id: ATT, name: 'In attesa di nuove uscite', color: '#c9e6fb', icon: 'cloud' },
    { id: FIN, name: 'Da finire',                 color: '#ffe3c8', icon: 'bookmark' },
    { id: LET, name: 'Letti',                     color: '#d6f0e0', icon: 'book' },
    { id: PRE, name: 'Preferiti finiti',          color: '#ffd7e6', icon: 'heart' },
    { id: SOS, name: 'Sospesi (non finiti)',      color: '#dee5fb', icon: 'sparkle' },
    { id: FOR, name: 'Sospesi — non so se finirli', color: '#eadffb', icon: 'moon' },
    { id: AUT, name: 'Autrici da seguire',        color: '#f7dcf2', icon: 'butterfly' }
  ];

  const books = [
    /* ---------- In attesa di nuove uscite ---------- */
    { t: 'I duchi della follia', a: '', c: [ATT], fav: true, vt: 5, n: 'Vol. 5 in uscita il 7 giugno' },
    { t: 'I ragazzi di Bellerose', a: 'Tate James', c: [ATT], vt: 4, n: 'Non ricordo dove sono arrivata' },
    { t: 'House of Night — Khaos series', a: 'Sophie Blackthorne', c: [ATT], vt: 2, vc: 2, n: 'Letti i vol. 1 e 2. Quando esce il vol. 3?' },
    { t: 'Crimson: Blood Revenge', a: 'S. Marty', c: [ATT, PRE], fav: true, read: true, vt: 1, vc: 1, n: 'Letto il vol. 1. Quando escono i vol. 2 e 3?' },
    { t: 'Crossline', a: 'S. Marty', c: [ATT], n: 'BELLOO — quando esce il vol. 2?' },
    { t: "The Witch's Knights", a: 'S. Marty', c: [ATT], fav: true, vt: 2, vc: 2, n: 'La leggenda del primo amore vol. 1, Il compagno vol. 2. Quando esce il vol. 3?' },
    { t: 'Legami di sangue', a: 'A. K. Rose', c: [ATT], fav: true, vt: 9, vc: 9, n: 'Letti dal vol. 1 al 9. Quando esce il vol. 10?' },
    { t: 'La guerra delle dieci regine — Urano Saga', a: 'Nisha J. Tuli', c: [ATT], vt: 3, vc: 1, pc: 198, n: 'Iniziato il vol. 1 a pag. 198. Quando escono i vol. 4 e 5?' },
    { t: 'Le spose dei naga', a: 'Naomi Lucas', c: [ATT, PRE], fav: true, read: true, vt: 4, vc: 4, n: 'Quando esce il vol. 5?' },
    { t: "L'omega perduta: La notte dei mostri", a: 'Lexi C. Foss', c: [ATT], vt: 1, n: 'Vol. 2 e 3 quando escono?' },
    { t: 'The Byrne Brothers', a: 'Jill Ramsower', c: [ATT, LET], read: true, vt: 1, vc: 1, n: 'Letto Silent Vows (vol. 1). Sono autoconclusivi — quando esce il vol. 2?' },
    { t: 'Storm and Sea', a: 'Deborah P. Cumberbatch', c: [ATT, PRE], fav: true, read: true, vt: 2, vc: 2, n: 'Quando esce il vol. 3???' },
    { t: "Winter Fe'", a: 'Ilaria Varese', c: [ATT, FIN], vt: 6, vc: 3, pc: 8, n: 'Ne devono uscire altri, voglio aspettare' },
    { t: 'Il cuore del lupo', a: 'G.D. Light', c: [ATT, FIN], vt: 5, vc: 2, n: 'Da leggere il vol. 2, ma sono a pagamento' },
    { t: 'Monsters After Dark', a: 'Meg Xuemei X', c: [ATT], vt: 3, n: 'Quando esce il vol. 3?' },
    { t: 'The Edge of Darkness', a: 'Leigh Rivers', c: [ATT, PRE], fav: true, vt: 3, vc: 2, n: 'Vol. 3 da leggere, esce il 30.06.26' },

    /* ---------- Autrici da seguire ---------- */
    { t: 'Chiaro di luna (retelling di Peter Pan)', a: 'Nina Talvi', c: [AUT], n: 'Prossima uscita di Nina Talvi?' },
    { t: 'Kat Blackthorne', a: 'Kat Blackthorne', c: [AUT], n: 'Nuovi libri in arrivo?' },
    { t: 'Nicole Fox', a: 'Nicole Fox', c: [AUT], n: 'Autrice da seguire — leggere altri libri' },
    { t: 'C. N. Crawford', a: 'C. N. Crawford', c: [AUT], n: 'Autrice da seguire — leggere altri libri' },
    { t: 'Pam Godwin', a: 'Pam Godwin', c: [AUT], n: 'Autrice da seguire — leggere altri libri' },
    { t: 'Chiara Cilli', a: 'Chiara Cilli', c: [AUT], n: 'Autrice da seguire — leggere altri libri' },
    { t: 'Sofia Mazzanti', a: 'Sofia Mazzanti', c: [AUT], n: 'Autrice da seguire — leggere altri libri' },
    { t: 'Olivia Wildenstein', a: 'Olivia Wildenstein', c: [AUT], n: 'Autrice da seguire — leggere altri libri' },

    /* ---------- Letti ---------- */
    { t: 'Regno di sangue — I sovrani dei bassifondi', a: '', c: [LET], read: true, vt: 3, vc: 3 },
    { t: 'La ragnatela del silenzio — Little Stranger, Little Liar', a: 'Leigh Rivers', c: [LET], read: true, vt: 2, vc: 2 },
    { t: 'House of Dark — Khaos series', a: 'Sophie Blackthorne', c: [LET], read: true },
    { t: 'Vuoi un passaggio — Ride or Die', a: 'Lauren Biel', c: [LET], read: true },
    { t: 'Reietti senza cuore', a: 'Santana Knox', c: [LET], read: true },
    { t: 'Blackridge Prep', a: 'A. R. Breck', c: [LET, SOS], read: true, vt: 3, vc: 3, n: 'Letti i vol. 1, 2 e 3. In sospeso: Sfide perverse vol. 1, restano i vol. 2 e 3' },
    { t: 'Brutale (mafia romance)', a: 'A. Coppola', c: [LET], read: true },
    { t: 'Trilogia delle anime', a: 'Harley Laroux', c: [LET], read: true, vt: 3, vc: 3 },
    { t: 'Il mio malessere', a: 'Nicole Blanchard', c: [LET], read: true },
    { t: 'Uncino — E se il cattivo…', a: 'Emily McIntire', c: [LET], read: true, vt: 6, vc: 6, n: 'Letti i vol. da 1 a 6. Quando esce il vol. 7?' },
    { t: 'Promesse e melagrane — Mostri e muse', a: 'San R. Miller', c: [LET, SOS], vt: 6, vc: 2, n: 'Letto il vol. 1. I vol. 2, 3, 4, 5, 6 sono sospesi' },
    { t: "I cavalieri dell'apocalisse", a: 'Laura Thalassa', c: [LET], read: true, vt: 4, vc: 4 },
    { t: 'The Crimson Thrones — Seth, Lugo, Nergal, Kàri', a: 'Laura Fiamenghi', c: [LET], read: true, vt: 4, vc: 4 },
    { t: "L'alba di Afrodite / La notte di Artemide", a: 'Barbara Reppetto, Laura Fiamenghi', c: [LET], read: true, vt: 2, vc: 2, n: "L'alba di Afrodite vol. 1 (Barbara Reppetto), La notte di Artemide vol. 2 (Laura Fiamenghi)" },
    { t: 'Storie di una nuova era', a: 'Norma Tarditi', c: [LET], read: true, vc: 5, n: 'Letti i vol. 1, 2, 3, 4, 5…' },
    { t: 'Black Peaches', a: 'S. Marty', c: [LET], read: true },
    { t: 'A Shadow Among the Lights', a: 'S. Marty', c: [LET], read: true },
    { t: 'Doppia anima — Double Soul e Abyssus', a: 'S. Marty', c: [LET], read: true, vt: 2, vc: 2 },
    { t: 'Hunting', a: 'S. Marty', c: [LET], read: true },
    { t: "Viking's Witch / Butterfly", a: 'S. Marty', c: [LET], read: true, vt: 2, vc: 2 },
    { t: 'Stars and Sand — Zendar, Guardiara, Resurra', a: 'Laura Fiamenghi', c: [LET], read: true, vt: 3, vc: 3 },
    { t: 'Clan dei vampiri di Darkfell', a: 'L.A. McGinnis', c: [LET], read: true, vt: 4, vc: 4 },
    { t: 'Il trono del lupo', a: 'Gea Petrini', c: [LET], read: true },
    { t: 'La stirpe del caos', a: 'M.D. Ferres', c: [LET], vt: 2, vc: 2, pc: 385, n: 'Vol. 2 sospeso a pag. 385' },
    { t: 'That Sik Luv', a: 'Jescie Hall', c: [LET], read: true },
    { t: 'È solo un gioco?', a: 'Harley Laroux', c: [LET], read: true, vt: 3, vc: 3 },
    { t: 'Santi e peccatori', a: 'Ruby Vincent', c: [LET], read: true, vt: 7, vc: 7 },
    { t: 'Royal Elite', a: 'Rina Kent', c: [LET], read: true, vt: 7, vc: 7 },
    { t: 'Kingdom Duet', a: 'Rina Kent', c: [LET], read: true, vt: 2, vc: 2 },
    { t: 'Darkside', a: 'S. Marty', c: [LET], read: true, vt: 2, vc: 2 },
    { t: 'Missing Part', a: 'S. Marty', c: [LET], read: true },
    { t: 'Her Demon Harem', a: 'Savannah Skye', c: [LET], read: true, vt: 2, vc: 2 },
    { t: 'La Bratva Zakrevsky', a: 'Nicole Fox', c: [LET], read: true, vt: 3, vc: 3 },
    { t: 'Enemy Arrow', a: 'Bea Hawks', c: [LET], read: true },
    { t: 'I quattro cavalieri', a: 'Sarah Bailey', c: [LET], read: true, vt: 4, vc: 4 },
    { t: 'La preda perfetta degli Alfa', a: 'Layla Sparks', c: [LET], read: true, vt: 2, vc: 2 },
    { t: 'She-Wolf', a: 'S. Marty', c: [LET], read: true },
    { t: 'Bloody Royals', a: 'Coralee June', c: [LET], read: true, vt: 3, vc: 3 },
    { t: 'Genesis — Wings of Vice series', a: 'Maria Antonietta Capasso', c: [LET], read: true, vt: 1, vc: 1, n: 'Usciranno altri volumi, quando?' },
    { t: 'Baci al veleno — Kiss of the Basilisk', a: 'Lindsay Straube', c: [LET], read: true },
    { t: 'Caos a Monsterland (rivisitazione di Alice nel Paese delle Meraviglie)', a: 'Lexi C. Foss', c: [LET], read: true },
    { t: 'Dark Provenance', a: 'Lexi C. Foss', c: [LET], vt: 3, vc: 1, n: 'Letto il vol. 1' },
    { t: 'Of Thorns and Starlight', a: 'Sofia Mazzanti', c: [LET], read: true },
    { t: 'Bond', a: 'S. Marty', c: [LET], read: true },
    { t: 'The Curvy 13 Playlist', a: 'Nicci Harris', c: [LET], read: true, vt: 3, vc: 3 },

    /* ---------- Da finire ---------- */
    { t: 'La serie Clecaniana', a: 'Victoria Aveline', c: [FIN], vt: 6, vc: 6, n: 'Da leggere il vol. 6' },
    { t: 'Agenzia Primaria', a: 'Regine Abel', c: [FIN], vt: 14, vc: 3, n: 'Da leggere il vol. 3' },
    { t: 'Blackwood Institute', a: 'J. Rose', c: [FIN], vt: 3, vc: 3, pc: 107, n: 'Vol. 3 a pag. 107' },
    { t: 'La setta Serendee', a: 'Angel Lawson', c: [FIN], vt: 3, vc: 2, n: 'Da leggere il vol. 2' },
    { t: 'Sinner Duet', a: 'Natasha Knight', c: [FIN], vt: 2, n: 'Leggere gli altri della serie' },
    { t: 'Omega Series', a: 'Giulia Rizzi', c: [FIN], vt: 2, vc: 2, n: 'Da leggere il vol. 2' },
    { t: 'Stars and Shadows', a: 'Holly Renee', c: [FIN, PRE], fav: true, vt: 4, vc: 4, n: 'Vol. 4 da leggere' },
    { t: "L'Alleanza — The Series", a: 'Hannon Rorke', c: [FIN], vt: 2, vc: 1, pc: 314, n: 'Vol. 1 a pag. 314. Sono autoconclusivi' },
    { t: 'Il suo branco reale di draghi', a: 'Alex Lidell', c: [FIN], vt: 4, vc: 2, pc: 49, n: 'Vol. 2 a pag. 49' },
    { t: 'I macellai di Blackwell', a: 'Sadie Hunt', c: [FIN], vt: 3, vc: 2, pc: 83, n: 'Vol. 2 a pag. 83' },
    { t: 'Inverno senza fine', a: 'K.T. Steen', c: [FIN], vt: 5, vc: 2, pc: 282, n: 'Vol. 2 a pag. 282' },
    { t: 'Chaos', a: 'Federica D.', c: [FIN], vt: 3, vc: 2, n: 'Da leggere il vol. 2' },

    /* ---------- Sospesi — non so se finirli ---------- */
    { t: 'I mutaforma di Grey Bridge', a: 'Reece Barden', c: [FOR], vt: 9, vc: 7, n: 'Da leggere il vol. 7' },
    { t: 'Steel Pack Alphas', a: 'Reece Barden', c: [FOR], vt: 3, vc: 2, n: 'Da leggere il vol. 2' },
    { t: 'La maledizione degli immortali', a: 'Lexi C. Foss', c: [FOR], vt: 9, vc: 2, n: 'Da leggere il vol. 2' },
    { t: 'Carnage Island — Artigli crudeli & Morsi proibiti', a: 'Lexi C. Foss', c: [FOR] },
    { t: 'La serie X-Clan', a: 'Lexi C. Foss', c: [FOR], vc: 4, pc: 186, n: 'Vol. 4 a pag. 186. Da leggere i vol. 5 e 6' },
    { t: 'Lupi V-Clan', a: 'Lexi C. Foss', c: [FOR], vt: 2, vc: 2, n: 'Da leggere i vol. 3 e 4' },
    { t: 'Squadra Alfa — Parte del branco', a: 'S. Marty', c: [FOR, SOS], vt: 11, vc: 7, n: 'Fermata al vol. 7, restano i vol. dal 7 all\'11' },
    { t: 'BrokenVerse (serie romantica omegaverse)', a: 'Charmaine Ross', c: [FOR], vt: 3, vc: 2, pc: 398, n: 'Letto solo il vol. 2, a pag. 398' },
    { t: 'Blood Bonds', a: 'Chiara Cilli', c: [FOR], vt: 11, vc: 3, pc: 4, n: 'Vol. 3 a pag. 4. Finisce con i protagonisti che si separano, come gli altri della serie' },
    { t: 'Padre', a: 'Clarissa Wild', c: [FOR], pc: 173, n: 'Fermata a pag. 173' },
    { t: 'Dolce Milli', a: 'Alexandra Art Club', c: [FOR], vt: 2, vc: 2, pc: 205, n: 'Vol. 2 a pag. 205' },
    { t: 'Serie Wildsong', a: "Tricia O'Malley", c: [FOR], vt: 4, vc: 2, n: 'Fermata al vol. 2' },
    { t: 'La regina degli inferi', a: 'Chiara Cilli', c: [FOR], vt: 1 },
    { t: 'Kings of Avalier', a: 'Leia Stone', c: [FOR], vt: 4, vc: 4, n: 'Da leggere il vol. 4' },
    { t: 'Alleanza di sangue', a: 'Lexi C. Foss', c: [FOR], vt: 7, vc: 2, n: 'Da leggere il vol. 2' },
    { t: 'Destinati al lupo', a: 'Gertty Rudraw', c: [FOR], vt: 4, vc: 1, pc: 257, pt: 278, n: 'Vol. 1 a pag. 257 di 278' },
    { t: 'La serie del rifiuto', a: 'Jaymin Snow', c: [FOR], vt: 3, vc: 3, n: 'Fermata al vol. 3' },
    { t: 'Serie Alpha Feroce', a: 'Jaymin Snow', c: [FOR], vc: 3, n: 'Vol. 3 da leggere' },

    /* ---------- Preferiti finiti ---------- */
    { t: 'Per inferos ad astra — Gli infernali', a: 'Nina Talvi', c: [PRE], fav: true, read: true, vt: 1, vc: 1 },
    { t: "Stirpe maledetta — Il bacio dell'incubo", a: 'Nina Talvi', c: [PRE], fav: true, read: true },
    { t: 'Stirpe maledetta — Il bacio della bestia', a: 'Nina Talvi', c: [PRE], fav: true, read: true },
    { t: "Stirpe maledetta — Il bacio dell'abisso", a: 'Nina Talvi', c: [PRE], fav: true, read: true },
    { t: "Eterno come la notte / Oscuro come l'abisso", a: 'Krisha Skies', c: [PRE], fav: true, read: true, vt: 2, vc: 2 },
    { t: 'Cronache divine — la serie completa', a: 'S. Marty', c: [PRE], fav: true, read: true },
    { t: 'Tale', a: 'S. Marty', c: [PRE], fav: true, read: true },
    { t: 'Kingdom / Freedom', a: 'S. Marty', c: [PRE], fav: true, read: true, vt: 2, vc: 2 },
    { t: 'Il gatto e il topo — Ti ho trovata Adeline / Ti ritroverò Adeline', a: 'H. D. Carlton', c: [PRE], fav: true, read: true, vt: 2, vc: 2 },
    { t: 'Deception', a: 'Rina Kent', c: [PRE], fav: true, read: true, vt: 3, vc: 3 },
    { t: 'Throne', a: 'Rina Kent', c: [PRE], fav: true, read: true, vt: 2, vc: 2 },
    { t: 'I ragazzi di Halloween', a: 'Kat Blackthorne', c: [PRE], fav: true, read: true, vt: 4, vc: 4 },
    { t: 'City of Thorns', a: 'C. N. Crawford', c: [PRE, SOS], fav: true, vt: 3, vc: 3, pc: 298, n: 'Vol. 3 a pag. 298' },
    { t: 'Il mare della rovina', a: 'Pam Godwin', c: [PRE], fav: true, read: true },
    { t: 'Feral — Heritage', a: 'Hannon Rorke', c: [PRE], fav: true, read: true, vt: 2, vc: 2 },
    { t: 'The Bridge Kingdom', a: 'Danielle L. Jensen', c: [PRE], fav: true, read: true, vt: 2, vc: 2 },
    { t: 'These Hollow Vows', a: 'Lexi Ryan', c: [PRE], fav: true, read: true, vt: 2, vc: 2, n: 'Non mi ha convinta al 100%' },
    { t: 'Black Sea', a: 'Chiara Cilli', c: [PRE], fav: true, read: true },
    { t: 'La promessa del leone', a: 'Chiara Cilli', c: [PRE], fav: true, read: true },
    { t: 'Il principe dei corvi', a: 'Gea Petrini', c: [PRE], fav: true, read: true },
    { t: 'Ti aspetterò per sempre — Pen Pal', a: 'J.T. Geissinger', c: [PRE], fav: true, read: true },
    { t: "L'ascesa dell'ammazza-fae", a: 'Sofia Mazzanti', c: [PRE], fav: true, read: true, vt: 4, vc: 4 },
    { t: 'I lupi di Boulder', a: 'Olivia Wildenstein', c: [PRE], fav: true, read: true, vt: 3, vc: 3 },
    { t: 'Thorns', a: 'Mary Jane Winter', c: [PRE], fav: true, read: true },

    /* ---------- Sospesi (non finiti) ---------- */
    { t: 'Hydra — Il segreto degli abissi', a: 'Barbara Riboni', c: [SOS] },
    { t: 'Clan dei vampiri di Shadowsend', a: 'L.A. McGinnis', c: [SOS], vc: 3, n: 'Sospesa al vol. 3' },
    { t: 'Secret Watch — La regina primordiale', a: 'Letty Frame', c: [SOS], vt: 1, vc: 1 },
    { t: 'Mutaforma maledetti', a: 'Charmaine Ross', c: [SOS], vt: 4, vc: 2, n: 'Letti i vol. 1 e 2, da leggere i vol. 3 e 4' },
    { t: 'Lilith — I dannati', a: 'K. V. Rose', c: [SOS], vt: 5, vc: 3, n: 'Vol. 3 in sospeso' },
    { t: 'Inked in Steel', a: 'Deborah P. Cumberbatch', c: [SOS] },
    { t: 'When the King Falls — La sposa di sangue', a: 'Marie Niehoff', c: [SOS], vt: 2, vc: 1, pc: 315, n: 'Vol. 1 a pag. 315' },
    { t: 'La discesa delle ombre', a: 'Eve Newton', c: [SOS], vt: 3, vc: 3, n: 'Vol. 3 da leggere' },
    { t: 'Regine omega selvagge', a: 'Ora Howl', c: [SOS], vt: 4, vc: 1, pc: 281, n: 'Vol. 1 a pag. 281' },
    { t: 'Black Claw Dragons (edizione italiana)', a: 'Lainie Anderson', c: [SOS], vt: 6, vc: 1, pc: 219, n: 'Vol. 1 a pag. 219' }
  ];

  window.SEED = { categories, books };
})();
